<?php 
require_once("models/document.inc");

function document_library_init(){
	define("DOCUMENT_LIBRARY_ROOT_PATH", drupal_get_path('module', 'document_library'));
}

/**
 * Implementation of hook_permission().
 */
function document_library_permission() {
	return array(
		"create documents"	=> array('title' => "Can Create documents"),
		"edit documents"	=> array('title' => "Can Edit documents"),
		"delete documents"	=> array('title' => "Can Delete documents"),
		"view documents"	=> array('title' => "Can View documents"),
	);
}

function document_library_check_permission($permission){
	global $user;
	return user_access($permission, $user);
}

function document_library_menu() {
	$items['document_library'] = array(
			'title'	=> 'Document Library',
			'description' => "View Document Library",
			'page arguments' => array(3),
			'page callback' => 'document_library_view',
			'file' => 'document_library.view.inc',
			'access callback' => 'document_library_check_permission',
			'access arguments' => array('view documents')
	);
	
	$items['document_library/fetch/%/%'] = array(
			'page arguments' => array(2),
			'page callback' => 'document_library_file_fetch',
			'file' => 'document_library.fetch.inc',
			'access callback' => TRUE,
	);
	
	$items['document_library/%/delete'] = array(
			'title'	=> 'Delete Document',
			'description' => "Delete a Document",
			'page arguments' => array(1),
			'page callback' => 'document_library_delete_document',
			'file' => 'document_library.admin.inc',
			'access callback' => 'document_library_check_permission',
			'access arguments' => array('delete documents')
	);
	
	$items['admin/document_library/edit/%'] = array(
			'title'	=> 'Edit document',
			'description' => "Edit a Document",
			'page arguments' => array(3),
			'page callback' => 'document_library_edit_document',
			'file' => 'document_library.admin.inc',
			'access callback' => 'document_library_check_permission',
			'access arguments' => array('edit documents')
	);
	
	$items['admin/document_library/add'] = array(
			'title'	=> 'Add new document',
			'description' => "Add a new Document",
			'page callback' => 'document_library_add_document',
			'file' => 'document_library.admin.inc',
			'access callback' => 'document_library_check_permission',
			'access arguments' => array('create documents')
	);

	return $items;
}


/**
 * Implements hook_block_info().
 */
function document_library_block_info() {
	$blocks['document_library'] = array(
			'info' => t('Document Library'), //The name that will appear in the block list.
			'cache' => DRUPAL_NO_CACHE // DRUPAL_CACHE_PER_ROLE, //Default
	);
	return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function document_library_block_view($delta = '') {
	switch($delta){
		case 'document_library':
			$block['subject'] = t('Document Center');
			$view = new StdClass();
			$view->documents = document::search()
				->order('created_date', 'DESC')
				->exec();
			$block['content'] = document_library_template_view(document_library_ROOT_PATH . "/templates/document_library.phtml", $view);
			return $block;
	}
}

/**
 * Crunch through a view
 * @param string $file File of the template to call.
 * @param array|object $view Optional view array.
 * @return string
 */
function document_library_template_view($file, $view = null){
	$file = DRUPAL_ROOT . "/" . $file;
	if(!file_exists($file)){
		return "Cannot find {$file}";
	}
	extract((array) $view);
	ob_start();
	require($file);
	$markup = ob_get_contents();
	ob_end_clean();
	return $markup;
}
