<div class="documents">
<?php 
// Show File Attachments to this question
$header = array();
$header[] = t('File name');
if(active_record_has_version_permission()){
	$header[] = t('Version');
}
$header[] = t('Description');
$header[] = t('Mimetype');
$header[] = t('Size');
$header[] = t('Last update');
$header[] = array(
		'data' => t('Operations'),
		'colspan' => document_library_check_permission('delete documents')?'2':'1'
);

$rows = array();
foreach ($documents as $document) {
	$row = array();
	
	$row[] = l($document->filename, $document->get_file_path());
	if(active_record_has_version_permission()){
		$row[] = $document->version;
	}	
	$row[] = $document->description;
	$row[] = _document_library_humanise_mimetype($document->mimetype);
	$row[] = round($document->size/1024,2) . "KB";
	$row[] = t("<b>@date</b> by <b>@author</b>", array(
					'@date' => date("Y/m/d",strtotime($document->created_date)),
					'@author' => $document->get_created_user()->name
	));
	$row[] = l("<span>" . t('Download') . "</span>", $document->get_file_path(), array('attributes' => array('class' => 'download'), 'html' => TRUE));
	if(document_library_check_permission('delete documents')){
		$row[] = l("<span>" . t('Delete') . "</span>", "document_library/{$document->get_slug()}/delete", array('attributes' => array('class' => 'delete'), 'html' => TRUE));
	}

	$rows[] = $row;
}
echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No documents available.')));
?>
</div>

<?php if(document_library_check_permission('create documents')):?>
	<form action="" method="POST" enctype="multipart/form-data">
		<fieldset>
			<legend>
				<div class="fieldset-legend"><?=t("Attach document:");?></div>
			</legend>
			<div class="fieldset-wrapper">
				<div class="form-item form-type-file">
					<label><?=t("Document")?>:</label>
					<input type="file" class="form-file" size="48" name="document">
					<div class="description"><?=t("A document that you wish to share.");?></div>
				</div>
				
				<div class="form-item form-type-textarea resizable">
					<label><?=t("Document Description")?></label>
					<div class="form-textarea-wrapper resizable textarea-processed resizable-textarea">
						<textarea class="form-textarea" name="description" cols="60" rows="5"></textarea>
						<div class="grippie"></div>
					</div>
				</div>
			</div>
		</fieldset>
		<div class="form-actions" id="edit-actions">
			<input type="submit" id="edit-submit" name="op" value="Upload" class="form-submit">
		</div>
	</form>
<?php endif; ?>	
